services:
  cornertonemanager:
    image: cornertonemanager
    build:
      context: .
      dockerfile: CornertoneManager/Dockerfile
  sqldata:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - SA_PASSWORD=Password2024
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
